"""Generate the native registry copier's component dispatch using stdlib only.

Component headers use unindented struct declarations in gw2combat::component;
indented nested payload structs are not independently registered components.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent


def main():
    includes = []
    components = []
    for path in sorted((ROOT / "src/component").rglob("*.hpp")):
        source = path.read_text(encoding="utf-8")
        names = re.findall(r"^struct\s+(\w+)\s*\{", source, re.MULTILINE)
        if names:
            if "namespace gw2combat::component {" not in source:
                raise ValueError(f"Unexpected component namespace in {path}")
            includes.append(f'#include "{path.relative_to(ROOT / "src").as_posix()}"')
            components.extend(names)
    if len(components) != len(set(components)):
        raise ValueError("Duplicate component declarations")

    cases = "\n".join(
        f"        case entt::type_hash<component::{name}>::value():\n"
        f"            return registry.storage<component::{name}>();"
        for name in components
    )
    code = '''// Generated by generate_copy_registry_utils.py; regenerate after adding components.
#include "registry_utils.hpp"

''' + "\n".join(includes) + '''

namespace gw2combat::utils {
namespace {

registry_t::base_type& assure_storage(registry_t& registry, entt::id_type id) {
    switch (id) {
''' + cases + '''
        default:
            throw std::runtime_error("Unregistered cache component; run generate_copy_registry_utils.py");
    }
}

}  // namespace

void copy_registry(const registry_t& source_registry, registry_t& destination_registry) {
    if (&source_registry == &destination_registry) {
        return;
    }
    destination_registry = registry_t{};
    // Include released identifiers, versions and the free list so future child/effect
    // allocations have exactly the same identities as an uninterrupted simulation.
    destination_registry.assign(source_registry.data(),
                                source_registry.data() + source_registry.size(),
                                source_registry.released());
    destination_registry.ctx() = source_registry.ctx();

    // Preserve each storage's packed order, not registry entity order. Systems use
    // this order for effects, counters, triggers and casts. Type-erased emplace
    // copies the value (including maps) and also supports empty marker components.
    for (auto&& [id, source] : source_registry.storage()) {
        auto& destination = assure_storage(destination_registry, id);
        if (source.policy() != entt::deletion_policy::swap_and_pop) {
            throw std::runtime_error("Cache copy requires packed component storage");
        }
        destination.reserve(source.size());
        for (auto it = source.rbegin(); it != source.rend(); ++it) {
            destination.emplace(*it, source.get(*it));
        }
    }
}

}  // namespace gw2combat::utils
'''
    path = ROOT / "src/utils/registry_utils.cpp"
    path.write_text(code, encoding="utf-8", newline="\n")
    print(f"Generated {path.relative_to(ROOT)} ({len(components)} component types)")


if __name__ == "__main__":
    main()
