// Generated by generate_copy_registry_utils.py; regenerate after adding components.
#include "registry_utils.hpp"

#include "component/actor/animation.hpp"
#include "component/actor/base_class_component.hpp"
#include "component/actor/begun_casting_skills.hpp"
#include "component/actor/combat_stats.hpp"
#include "component/actor/destroy_after_rotation.hpp"
#include "component/actor/finished_casting_skills.hpp"
#include "component/actor/is_actor.hpp"
#include "component/actor/is_cooldown_modifier.hpp"
#include "component/actor/is_downstate.hpp"
#include "component/actor/no_more_rotation.hpp"
#include "component/actor/profession_component.hpp"
#include "component/actor/relative_attributes.hpp"
#include "component/actor/rotation_component.hpp"
#include "component/actor/skills_actions_component.hpp"
#include "component/actor/skills_ticks_tracker_component.hpp"
#include "component/actor/static_attributes.hpp"
#include "component/actor/team.hpp"
#include "component/attributes/is_attribute_conversion.hpp"
#include "component/attributes/is_attribute_modifier.hpp"
#include "component/audit/audit_component.hpp"
#include "component/counter/is_counter.hpp"
#include "component/counter/is_counter_modifier.hpp"
#include "component/damage/buffered_condition_damage.hpp"
#include "component/damage/effects_pipeline.hpp"
#include "component/damage/incoming_damage.hpp"
#include "component/damage/strikes_pipeline.hpp"
#include "component/effect/is_effect.hpp"
#include "component/effect/is_effect_removal.hpp"
#include "component/effect/is_skill_trigger.hpp"
#include "component/effect/is_unique_effect.hpp"
#include "component/effect/source_actor.hpp"
#include "component/effect/source_skill.hpp"
#include "component/encounter/encounter_configuration_component.hpp"
#include "component/encounter/random_state.hpp"
#include "component/equipment/bundle.hpp"
#include "component/equipment/weapons.hpp"
#include "component/hierarchy/owner_component.hpp"
#include "component/lifecycle/destroy_entity.hpp"
#include "component/skill/ammo.hpp"
#include "component/skill/is_conditional_skill_group.hpp"
#include "component/skill/is_skill.hpp"
#include "component/temporal/animation_component.hpp"
#include "component/temporal/cooldown_component.hpp"
#include "component/temporal/duration_component.hpp"
#include "component/temporal/has_alacrity.hpp"
#include "component/temporal/has_quickness.hpp"

namespace gw2combat::utils {
namespace {

registry_t::base_type& assure_storage(registry_t& registry, entt::id_type id) {
    switch (id) {
        case entt::type_hash<component::animation>::value():
            return registry.storage<component::animation>();
        case entt::type_hash<component::base_class_component>::value():
            return registry.storage<component::base_class_component>();
        case entt::type_hash<component::begun_casting_skills>::value():
            return registry.storage<component::begun_casting_skills>();
        case entt::type_hash<component::combat_stats>::value():
            return registry.storage<component::combat_stats>();
        case entt::type_hash<component::combat_stats_updated>::value():
            return registry.storage<component::combat_stats_updated>();
        case entt::type_hash<component::destroy_after_rotation>::value():
            return registry.storage<component::destroy_after_rotation>();
        case entt::type_hash<component::finished_casting_skills>::value():
            return registry.storage<component::finished_casting_skills>();
        case entt::type_hash<component::already_finished_casting_skill>::value():
            return registry.storage<component::already_finished_casting_skill>();
        case entt::type_hash<component::is_actor>::value():
            return registry.storage<component::is_actor>();
        case entt::type_hash<component::actor_created>::value():
            return registry.storage<component::actor_created>();
        case entt::type_hash<component::is_cooldown_modifier_t>::value():
            return registry.storage<component::is_cooldown_modifier_t>();
        case entt::type_hash<component::is_downstate>::value():
            return registry.storage<component::is_downstate>();
        case entt::type_hash<component::no_more_rotation>::value():
            return registry.storage<component::no_more_rotation>();
        case entt::type_hash<component::profession_component>::value():
            return registry.storage<component::profession_component>();
        case entt::type_hash<component::relative_attributes>::value():
            return registry.storage<component::relative_attributes>();
        case entt::type_hash<component::rotation_component>::value():
            return registry.storage<component::rotation_component>();
        case entt::type_hash<component::already_performed_rotation>::value():
            return registry.storage<component::already_performed_rotation>();
        case entt::type_hash<component::skills_actions_component>::value():
            return registry.storage<component::skills_actions_component>();
        case entt::type_hash<component::finished_skills_actions_component>::value():
            return registry.storage<component::finished_skills_actions_component>();
        case entt::type_hash<component::skills_ticks_tracker_component>::value():
            return registry.storage<component::skills_ticks_tracker_component>();
        case entt::type_hash<component::destroy_skills_ticks_tracker_component>::value():
            return registry.storage<component::destroy_skills_ticks_tracker_component>();
        case entt::type_hash<component::static_attributes>::value():
            return registry.storage<component::static_attributes>();
        case entt::type_hash<component::team>::value():
            return registry.storage<component::team>();
        case entt::type_hash<component::is_attribute_conversion>::value():
            return registry.storage<component::is_attribute_conversion>();
        case entt::type_hash<component::is_attribute_modifier>::value():
            return registry.storage<component::is_attribute_modifier>();
        case entt::type_hash<component::audit_component>::value():
            return registry.storage<component::audit_component>();
        case entt::type_hash<component::is_counter>::value():
            return registry.storage<component::is_counter>();
        case entt::type_hash<component::is_counter_modifier_t>::value():
            return registry.storage<component::is_counter_modifier_t>();
        case entt::type_hash<component::condition_damage_t>::value():
            return registry.storage<component::condition_damage_t>();
        case entt::type_hash<component::buffered_condition_damage>::value():
            return registry.storage<component::buffered_condition_damage>();
        case entt::type_hash<component::effect_application_t>::value():
            return registry.storage<component::effect_application_t>();
        case entt::type_hash<component::outgoing_effects_component>::value():
            return registry.storage<component::outgoing_effects_component>();
        case entt::type_hash<component::incoming_effect_application>::value():
            return registry.storage<component::incoming_effect_application>();
        case entt::type_hash<component::incoming_effects_component>::value():
            return registry.storage<component::incoming_effects_component>();
        case entt::type_hash<component::incoming_damage_event>::value():
            return registry.storage<component::incoming_damage_event>();
        case entt::type_hash<component::incoming_damage>::value():
            return registry.storage<component::incoming_damage>();
        case entt::type_hash<component::strike_t>::value():
            return registry.storage<component::strike_t>();
        case entt::type_hash<component::outgoing_strikes_component>::value():
            return registry.storage<component::outgoing_strikes_component>();
        case entt::type_hash<component::incoming_strike>::value():
            return registry.storage<component::incoming_strike>();
        case entt::type_hash<component::incoming_strikes_component>::value():
            return registry.storage<component::incoming_strikes_component>();
        case entt::type_hash<component::is_effect>::value():
            return registry.storage<component::is_effect>();
        case entt::type_hash<component::is_damaging_effect>::value():
            return registry.storage<component::is_damaging_effect>();
        case entt::type_hash<component::is_effect_removal_t>::value():
            return registry.storage<component::is_effect_removal_t>();
        case entt::type_hash<component::is_skill_trigger>::value():
            return registry.storage<component::is_skill_trigger>();
        case entt::type_hash<component::is_unchained_skill_trigger>::value():
            return registry.storage<component::is_unchained_skill_trigger>();
        case entt::type_hash<component::is_source_actor_skill_trigger>::value():
            return registry.storage<component::is_source_actor_skill_trigger>();
        case entt::type_hash<component::is_unique_effect>::value():
            return registry.storage<component::is_unique_effect>();
        case entt::type_hash<component::source_actor>::value():
            return registry.storage<component::source_actor>();
        case entt::type_hash<component::source_skill>::value():
            return registry.storage<component::source_skill>();
        case entt::type_hash<component::encounter_configuration_component>::value():
            return registry.storage<component::encounter_configuration_component>();
        case entt::type_hash<component::random_state_t>::value():
            return registry.storage<component::random_state_t>();
        case entt::type_hash<component::bundle_component>::value():
            return registry.storage<component::bundle_component>();
        case entt::type_hash<component::equipped_bundle>::value():
            return registry.storage<component::equipped_bundle>();
        case entt::type_hash<component::dropped_bundle>::value():
            return registry.storage<component::dropped_bundle>();
        case entt::type_hash<component::weapon_t>::value():
            return registry.storage<component::weapon_t>();
        case entt::type_hash<component::equipped_weapons>::value():
            return registry.storage<component::equipped_weapons>();
        case entt::type_hash<component::current_weapon_set>::value():
            return registry.storage<component::current_weapon_set>();
        case entt::type_hash<component::owner_component>::value():
            return registry.storage<component::owner_component>();
        case entt::type_hash<component::destroy_entity>::value():
            return registry.storage<component::destroy_entity>();
        case entt::type_hash<component::ammo>::value():
            return registry.storage<component::ammo>();
        case entt::type_hash<component::ammo_gained>::value():
            return registry.storage<component::ammo_gained>();
        case entt::type_hash<component::is_conditional_skill_group>::value():
            return registry.storage<component::is_conditional_skill_group>();
        case entt::type_hash<component::is_part_of_conditional_skill_group>::value():
            return registry.storage<component::is_part_of_conditional_skill_group>();
        case entt::type_hash<component::is_skill>::value():
            return registry.storage<component::is_skill>();
        case entt::type_hash<component::animation_component>::value():
            return registry.storage<component::animation_component>();
        case entt::type_hash<component::already_performed_animation>::value():
            return registry.storage<component::already_performed_animation>();
        case entt::type_hash<component::animation_expired>::value():
            return registry.storage<component::animation_expired>();
        case entt::type_hash<component::is_afk>::value():
            return registry.storage<component::is_afk>();
        case entt::type_hash<component::cooldown_component>::value():
            return registry.storage<component::cooldown_component>();
        case entt::type_hash<component::cooldown_expired>::value():
            return registry.storage<component::cooldown_expired>();
        case entt::type_hash<component::duration_component>::value():
            return registry.storage<component::duration_component>();
        case entt::type_hash<component::duration_expired>::value():
            return registry.storage<component::duration_expired>();
        case entt::type_hash<component::has_alacrity>::value():
            return registry.storage<component::has_alacrity>();
        case entt::type_hash<component::has_quickness>::value():
            return registry.storage<component::has_quickness>();
        default:
            throw std::runtime_error("Unregistered cache component; run generate_copy_registry_utils.py");
    }
}

}  // namespace

void copy_registry(const registry_t& source_registry, registry_t& destination_registry) {
    if (&source_registry == &destination_registry) {
        return;
    }
    destination_registry = registry_t{};
    // Include released identifiers, versions and the free list so future child/effect
    // allocations have exactly the same identities as an uninterrupted simulation.
    destination_registry.assign(source_registry.data(),
                                source_registry.data() + source_registry.size(),
                                source_registry.released());
    destination_registry.ctx() = source_registry.ctx();

    // Preserve each storage's packed order, not registry entity order. Systems use
    // this order for effects, counters, triggers and casts. Type-erased emplace
    // copies the value (including maps) and also supports empty marker components.
    for (auto&& [id, source] : source_registry.storage()) {
        auto& destination = assure_storage(destination_registry, id);
        if (source.policy() != entt::deletion_policy::swap_and_pop) {
            throw std::runtime_error("Cache copy requires packed component storage");
        }
        destination.reserve(source.size());
        for (auto it = source.rbegin(); it != source.rend(); ++it) {
            destination.emplace(*it, source.get(*it));
        }
    }
}

}  // namespace gw2combat::utils
